module.exports = {
    WISDOM:"0001",
    SCOUTING:"0002",
    CREATING:"0003",
    HEALING:"0004",
    INSIGHT:"0005",
    LUCKY:"0006",
    NATURE:"0007",
    COURAGE:"0008",
    INTELLIGENCE:"0009",
    MEMERY:"",
    GLAMOUR:"",
    TACTICS:"",
    MAGIC:"",
    MYSTERY:"",
    FAITH:"",
    WATER_MAGIC:"",
    FIRE_MAGIC:"",
    LIGHT_MAGIC:"",
    MAGIC_MASTERY:"",
    WEAPON_MASTERY:"",
    STRONG:"",
    COMBAT_SKILL:"",
    BALLISTICS:"",
    ESTATES:"",
    NECROMANCY:"",

};